import './globals.css'
import type { Metadata } from 'next'
import {Inter, Roboto} from 'next/font/google'
import Header from "@/components/Header/Header";
import Sidebar from "@/components/Sidebar/Sidebar";

const roboto = Roboto({weight:"400", subsets:["latin"]})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`text-primary_text bg-background_main text-lg ${roboto.className}`}>
        <Header/>
        <Sidebar/>
        <main className={"pl-60"}>
          {children}
        </main>
      </body>
    </html>
  )
}
